# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge
# highlighter: pygments

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Rowan MemSat'
tagline:          ''
description:      'A portal for all things MemSat.'
#url:              'http://localhost:4000'
#baseurl:          ''
url:              'http://memsat.space'
baseurl:          ''
icon:             '/assets/images/memsat_logo2_1024.png'

# Navigation
navigation:
- text: About
  url: /about/
- text: Docs
  url: /docs/
- text: Launch
  url: /launch/
- text: Updates
  url: /updates/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/
  
navigation_docs:
- text: Docs Home
  url: /docs/
- text: Motherboard
  url: /docs/api/
- text: Doc Generator
  url: /docs/pyrmd/
- text: UART
  url: /docs/uart/
- text: Tests
  url: /docs/test/
- text: -API Reference-
  url: #
- text: Motherboard
  url: /docs/motherboard


# Author Details
author:         'Christopher Frederickson'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       'https://www.facebook.com/RowanECE/'
flickr:
github:         ''
gplus:          ''
instagram:
pinterest:
linkedin:       ''
rss:
stackoverflow:  ''
twitter:        ''

# Google Analytics
gahandler: ''

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'false'

# Disqus
disqushandler: ''

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/updates/page:num'
destination: ./_site

# Custom vars
version:          0.1
